meta_product_name: “MIX\MATE”

meta_title: “MIX\MATE - Personalized Playlists Made Easy”

meta_description: “Discover MIX\MATE, where music meets innovation. Create, customize, and share your unique playlists effortlessly. Join the community that's reshaping the way we experience music!”

meta_image: "cover.png" # should exist in `app/assets/images/`
